# Site Settings
title: "Live TV Malaysia Online"
seo_title: "Live TV Malaysia Online - HD Streaming & 2026 Live Sports"
description: "Watch all Malaysian TV channels live online for free."
url: "https://www.livetvmalaysia.site"
baseurl: "" 

google_verify: "AClBoYkUfOFJsqDelDrrWx5Rs1KVVVOJQQlW0fiX_9A"
bing_verify: "2023033E7A81CF57AE17074D2DAC523D"

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Pagination V2
pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/' 
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true


autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'list.html' # Layout yang akan digunakan untuk halaman kategori
    title: 'Live Streaming :categories'
    permalink: '/category/:category/'
